import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import WalletContextProvider from "../components/WalletContextProvider"
import { AppBar } from "../components/AppBar"
import { SendSolForm } from "../components/SendSolForm"
import { PagoEmpleado } from "../components/PagoEmpleado"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
          <div className={styles.App}>
      <Head>
        <title>FastPay</title>
      </Head>
      <WalletContextProvider>
        <div className={styles.background}>
          <AppBar />
          <div className={styles.AppBody}>
            <SendSolForm />
            <PagoEmpleado />
          </div>
        </div>
      </WalletContextProvider>
    </div>
              
            
          </div>
        </div>

        
      </main>
    </>
  )
}
